// Code generated by go-swagger; DO NOT EDIT.

package apimodel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Company company
//
// swagger:model Company
type Company struct {

	// account id
	AccountID int64 `json:"account_id,omitempty"`

	// created at
	CreatedAt int64 `json:"created_at,omitempty"`

	// created by
	CreatedBy int64 `json:"created_by,omitempty"`

	// custom fields values
	CustomFieldsValues []*CustomFieldsValue `json:"custom_fields_values"`

	// group id
	GroupID int64 `json:"group_id,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// is deleted
	IsDeleted bool `json:"is_deleted,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// responsible user id
	ResponsibleUserID int64 `json:"responsible_user_id,omitempty"`

	// updated at
	UpdatedAt int64 `json:"updated_at,omitempty"`

	// updated by
	UpdatedBy int64 `json:"updated_by,omitempty"`
}

// Validate validates this company
func (m *Company) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCustomFieldsValues(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Company) validateCustomFieldsValues(formats strfmt.Registry) error {
	if swag.IsZero(m.CustomFieldsValues) { // not required
		return nil
	}

	for i := 0; i < len(m.CustomFieldsValues); i++ {
		if swag.IsZero(m.CustomFieldsValues[i]) { // not required
			continue
		}

		if m.CustomFieldsValues[i] != nil {
			if err := m.CustomFieldsValues[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("custom_fields_values" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this company based on the context it is used
func (m *Company) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCustomFieldsValues(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Company) contextValidateCustomFieldsValues(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.CustomFieldsValues); i++ {

		if m.CustomFieldsValues[i] != nil {
			if err := m.CustomFieldsValues[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("custom_fields_values" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Company) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Company) UnmarshalBinary(b []byte) error {
	var res Company
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
