// Code generated by go-swagger; DO NOT EDIT.

package apimodel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CompaniesAddResponse companies add response
//
// swagger:model CompaniesAddResponse
type CompaniesAddResponse struct {

	// embedded
	Embedded *CompaniesAddResponseEmbedded `json:"_embedded,omitempty"`
}

// Validate validates this companies add response
func (m *CompaniesAddResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEmbedded(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CompaniesAddResponse) validateEmbedded(formats strfmt.Registry) error {
	if swag.IsZero(m.Embedded) { // not required
		return nil
	}

	if m.Embedded != nil {
		if err := m.Embedded.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("_embedded")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this companies add response based on the context it is used
func (m *CompaniesAddResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateEmbedded(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CompaniesAddResponse) contextValidateEmbedded(ctx context.Context, formats strfmt.Registry) error {

	if m.Embedded != nil {
		if err := m.Embedded.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("_embedded")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CompaniesAddResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CompaniesAddResponse) UnmarshalBinary(b []byte) error {
	var res CompaniesAddResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// CompaniesAddResponseEmbedded companies add response embedded
//
// swagger:model CompaniesAddResponseEmbedded
type CompaniesAddResponseEmbedded struct {

	// companies
	Companies []*CompaniesAddResponseEmbeddedCompaniesItems0 `json:"companies"`
}

// Validate validates this companies add response embedded
func (m *CompaniesAddResponseEmbedded) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCompanies(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CompaniesAddResponseEmbedded) validateCompanies(formats strfmt.Registry) error {
	if swag.IsZero(m.Companies) { // not required
		return nil
	}

	for i := 0; i < len(m.Companies); i++ {
		if swag.IsZero(m.Companies[i]) { // not required
			continue
		}

		if m.Companies[i] != nil {
			if err := m.Companies[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("_embedded" + "." + "companies" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this companies add response embedded based on the context it is used
func (m *CompaniesAddResponseEmbedded) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCompanies(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CompaniesAddResponseEmbedded) contextValidateCompanies(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Companies); i++ {

		if m.Companies[i] != nil {
			if err := m.Companies[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("_embedded" + "." + "companies" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *CompaniesAddResponseEmbedded) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CompaniesAddResponseEmbedded) UnmarshalBinary(b []byte) error {
	var res CompaniesAddResponseEmbedded
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// CompaniesAddResponseEmbeddedCompaniesItems0 companies add response embedded companies items0
//
// swagger:model CompaniesAddResponseEmbeddedCompaniesItems0
type CompaniesAddResponseEmbeddedCompaniesItems0 struct {

	// id
	ID int64 `json:"id,omitempty"`

	// is deleted
	IsDeleted bool `json:"is_deleted,omitempty"`

	// request id
	RequestID string `json:"request_id,omitempty"`
}

// Validate validates this companies add response embedded companies items0
func (m *CompaniesAddResponseEmbeddedCompaniesItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this companies add response embedded companies items0 based on context it is used
func (m *CompaniesAddResponseEmbeddedCompaniesItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CompaniesAddResponseEmbeddedCompaniesItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CompaniesAddResponseEmbeddedCompaniesItems0) UnmarshalBinary(b []byte) error {
	var res CompaniesAddResponseEmbeddedCompaniesItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
