// Code generated by go-swagger; DO NOT EDIT.

package apimodel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CustomFieldRequiredStatus custom field required status
//
// swagger:model CustomFieldRequiredStatus
type CustomFieldRequiredStatus struct {

	// pipeline id
	PipelineID int64 `json:"pipeline_id,omitempty"`

	// status id
	StatusID int64 `json:"status_id,omitempty"`
}

// Validate validates this custom field required status
func (m *CustomFieldRequiredStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this custom field required status based on context it is used
func (m *CustomFieldRequiredStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CustomFieldRequiredStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustomFieldRequiredStatus) UnmarshalBinary(b []byte) error {
	var res CustomFieldRequiredStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
