// Code generated by go-swagger; DO NOT EDIT.

package apimodel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EditResponse edit response
//
// swagger:model EditResponse
type EditResponse struct {

	// id
	ID int64 `json:"id,omitempty"`

	// request id
	RequestID string `json:"request_id,omitempty"`

	// updated at
	UpdatedAt int64 `json:"updated_at,omitempty"`
}

// Validate validates this edit response
func (m *EditResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this edit response based on context it is used
func (m *EditResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EditResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EditResponse) UnmarshalBinary(b []byte) error {
	var res EditResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
