// Code generated by go-swagger; DO NOT EDIT.

package apimodel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EntityLinksAdd entity links add
//
// swagger:model EntityLinksAdd
type EntityLinksAdd []*EntityLinksAddItems0

// Validate validates this entity links add
func (m EntityLinksAdd) Validate(formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(m); i++ {
		if swag.IsZero(m[i]) { // not required
			continue
		}

		if m[i] != nil {
			if err := m[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName(strconv.Itoa(i))
				}
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this entity links add based on the context it is used
func (m EntityLinksAdd) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(m); i++ {

		if m[i] != nil {
			if err := m[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName(strconv.Itoa(i))
				}
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// EntityLinksAddItems0 entity links add items0
//
// swagger:model EntityLinksAddItems0
type EntityLinksAddItems0 struct {

	// metadata
	Metadata *EntityLinksAddItems0Metadata `json:"metadata,omitempty"`

	// to entity id
	ToEntityID int64 `json:"to_entity_id,omitempty"`

	// to entity type
	ToEntityType string `json:"to_entity_type,omitempty"`
}

// Validate validates this entity links add items0
func (m *EntityLinksAddItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMetadata(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EntityLinksAddItems0) validateMetadata(formats strfmt.Registry) error {
	if swag.IsZero(m.Metadata) { // not required
		return nil
	}

	if m.Metadata != nil {
		if err := m.Metadata.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("metadata")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this entity links add items0 based on the context it is used
func (m *EntityLinksAddItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMetadata(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EntityLinksAddItems0) contextValidateMetadata(ctx context.Context, formats strfmt.Registry) error {

	if m.Metadata != nil {
		if err := m.Metadata.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("metadata")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *EntityLinksAddItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EntityLinksAddItems0) UnmarshalBinary(b []byte) error {
	var res EntityLinksAddItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// EntityLinksAddItems0Metadata entity links add items0 metadata
//
// swagger:model EntityLinksAddItems0Metadata
type EntityLinksAddItems0Metadata struct {

	// catalog id
	CatalogID int64 `json:"catalog_id,omitempty"`

	// is main
	IsMain bool `json:"is_main,omitempty"`

	// price id
	PriceID int64 `json:"price_id,omitempty"`

	// quantity
	Quantity int64 `json:"quantity,omitempty"`

	// updated by
	UpdatedBy int64 `json:"updated_by,omitempty"`
}

// Validate validates this entity links add items0 metadata
func (m *EntityLinksAddItems0Metadata) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this entity links add items0 metadata based on context it is used
func (m *EntityLinksAddItems0Metadata) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EntityLinksAddItems0Metadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EntityLinksAddItems0Metadata) UnmarshalBinary(b []byte) error {
	var res EntityLinksAddItems0Metadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
