// Code generated by go-swagger; DO NOT EDIT.

package apimodel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NoteParams note params
//
// swagger:model NoteParams
type NoteParams struct {

	// address
	Address string `json:"address,omitempty"`

	// duration
	Duration int64 `json:"duration,omitempty"`

	// latitude
	Latitude string `json:"latitude,omitempty"`

	// link
	Link string `json:"link,omitempty"`

	// longitude
	Longitude string `json:"longitude,omitempty"`

	// phone
	Phone string `json:"phone,omitempty"`

	// service
	Service string `json:"service,omitempty"`

	// source
	Source string `json:"source,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// text
	Text string `json:"text,omitempty"`

	// uniq
	Uniq string `json:"uniq,omitempty"`
}

// Validate validates this note params
func (m *NoteParams) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this note params based on context it is used
func (m *NoteParams) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NoteParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NoteParams) UnmarshalBinary(b []byte) error {
	var res NoteParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
