// Code generated by go-swagger; DO NOT EDIT.

package apimodel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OAuth2Req o auth2 req
//
// swagger:model OAuth2Req
type OAuth2Req struct {

	// client id
	ClientID string `json:"client_id,omitempty"`

	// client secret
	ClientSecret string `json:"client_secret,omitempty"`

	// code
	Code string `json:"code,omitempty"`

	// grant type
	GrantType string `json:"grant_type,omitempty"`

	// redirect uri
	RedirectURI string `json:"redirect_uri,omitempty"`

	// refresh token
	RefreshToken string `json:"refresh_token,omitempty"`
}

// Validate validates this o auth2 req
func (m *OAuth2Req) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this o auth2 req based on context it is used
func (m *OAuth2Req) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OAuth2Req) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OAuth2Req) UnmarshalBinary(b []byte) error {
	var res OAuth2Req
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
