// Code generated by go-swagger; DO NOT EDIT.

package apimodel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OAuth2Res o auth2 res
//
// swagger:model OAuth2Res
type OAuth2Res struct {

	// access token
	AccessToken string `json:"access_token,omitempty"`

	// expires in
	ExpiresIn int64 `json:"expires_in,omitempty"`

	// refresh token
	RefreshToken string `json:"refresh_token,omitempty"`

	// token type
	TokenType string `json:"token_type,omitempty"`
}

// Validate validates this o auth2 res
func (m *OAuth2Res) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this o auth2 res based on context it is used
func (m *OAuth2Res) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OAuth2Res) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OAuth2Res) UnmarshalBinary(b []byte) error {
	var res OAuth2Res
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
